### ISSUE TITLE
Lots of errors when compiling with gcc in Linux

### ISSUE THREAD

**Issue by sheosi** [nothings/obbg#4]
I know this does not works on Linux, but I wanted to  give it a try (as self-training in C and 3d) however I got tons of warnings and errors:
https://gist.github.com/sheosi/e67a92b9677756ee60fd
They seem to come from everywhere.

For completeness sake those are the modifications I made:
1. Removed #include <windows.h> from master
2. In stb_gl renamed <gl/gl.h> to <GL/gl.h>
3. In stb/ added files sdl.h and sdl_thread.h which include <SDL.h> and <SDL_thread.h> respectively lazy workaround for case sensitve systems)

And used this line:
gcc -o obbg -D_GNU_SOURCE=1 -D_REENTRANT -Isrc/3rd -Isrc/win32 -I/usr/include/SDL -I/usr/include/libdrm -Istb -Istb/tests/caveview src/main.c src/mesh_builder.c src/u_noise.c src/voxel_render.c
( -D_GNU_SOURCE=1, -D_REENTRANT and  -I/usr/include/libdrm are there because pkg-config told me to add them, tried without them and it's pretty much the same).

**Comment by nothings** [comment]
Ok, it looks like this is actually a reasonably small number of issues repeated:
1. stb.h has a bunch of issues with converting between int and void*, which is because it has never been properly ported to 64-bit; it would possibly work if you compiled in 32-bit. (Note that OBBG probably isn't using those parts of stb.h anyway.)
2. a lot of errors to do with OpenGL extensions. one is that we're declaring a lot of OpenGL function names that have conflicts in Linux; that's because the Windows OpenGL headers are only 1.1, so there are no conflicting symbols for any names after that. so that stuff needs to have a Linux/Windows #ifdef to know which symbols already exist (this would go in glext_list.h, I think).
3. But even with the above it'll probably be broken because stb_gl.h has its own extension handling system which is I think hard-coded to do it through Windows, so any attempt to access extensions on other platforms is still going to fail to compile.
4. There's some SDL-related errors; the only thing I can think of is that you're using SDL 1, whereas this project uses SDL 2.
5. some const char vs. char errors

I'll try and fix these (except #4) when I get a chance.

**Comment by sheosi** [comment]
That's rihgt, I thought (wrongly) that you were using SDL 1, if you are interested I can try to recompile wiht 32 bits and SDL 2, also I can try it with clang.

**Comment by nothings** [comment]
Yes, if you can try building w/ SDL2 and 32-bit that would be interesting (but I do need to fix the 64-bit case regardless).

**Comment by sheosi** [comment]
Here you are:
https://gist.github.com/sheosi/3b6bf01a4fc878c1f7a3

BTW, it would be nice if you solved the errors I workarounded before:
<gl/...> to <GL/...>,  and <sdl...> to <SDL...>.
(BTW, edited the first comment didn't knew github did odd things with <)

**Comment by Sofahamster** [comment]
Not sure if this is still relevant, but it does compile as 64-bit with the new VS2015 compiler and SDL 2.0.3 (using CMake+Ninja).

**Comment by nothings** [comment]
stb.h received a bunch of 64-bit fixes, although I don't remember if I propagated them into this project. I guess I did?

**Comment by Sofahamster** [comment]
I used stb.h from the stb repository, so that might be it. I hadn't even noticed the stb folder in the obbg repo until after you mentioned it.

**Comment by mgerhardy** [comment]
@Sofahamster can you maybe provide the CMakeLists.txt - that would make my life easier on linux, too ;)

**Comment by insofaras** [comment]
I got it building with gcc on linux (32-bit), see #8

**Comment by sheosi** [comment]
It works fine now, closing.
